### PR TITLE
Overview: bug fixing, cleanup

### PR DESCRIPTION
**Pull request by zxl3269117**

### CODE REVIEW

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
- Fix bug in initial rendering of ImageGallery
- Code clean up

**Comment by zxl3269117** [comment]
- Code clean up
- Add color to sales price
- Fixed bug rendering rating

**Review by davidltruong — APPROVED** [review]
Looks good to me

**Review by mpmanzo — APPROVED** [review]
Looks good

**Pull request merged**
