### PR TITLE
add functions and fix one cart bug

### PR DESCRIPTION
**Pull request by zxl3269117**

### CODE REVIEW

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
- Adding this branch to work on a version without the clickTracker
- Added the function in ProductInfo to click on "read all # reviews"
- Removed one function of "Add to cart" button that return to default, set it as a stretch goal

**Review by mpmanzo — COMMENTED** [review]
Where are you finding the '#' leading into the productId?

**Review by mpmanzo — APPROVED** [review]
Looks good.

**Comment by zxl3269117** [comment]
> Where are you finding the '#' leading into the productId?

If you're talking about '#' in the "read all # reviews", it's just representing the total number of reviews.
The '#' in the anchor <a> element that wraps around  "read all # reviews" with the '#' that allows jumping to the review section of the page, the '#' was able to be taken out of the page in the `server/index.html` codes.
Does these answer your question?

**Comment by mpmanzo** [comment]
> > Where are you finding the '#' leading into the productId?
> 
> If you're talking about '#' in the "read all # reviews", it's just representing the total number of reviews. The '#' in the anchor element that wraps around "read all # reviews" with the '#' that allows jumping to the review section of the page, the '#' was able to be taken out of the page in the `server/index.html` codes. Does these answer your question?

No, I'm referring to the '#' being stripped from the front of the productId, if it exists, in server/index.html file. I'm just wondering if it was found in some data from the API or if we're adding it somewhere.

`<script>
      var productId = window.location.href.split('/')[3];
      if(productId.includes('#')) {
      productId = productId.split('#')[0];
      window.history.replaceState('object or string', 'Title', productId);
    }

  </script>`

**Comment by zxl3269117** [comment]
> 

Sure. The '#' is added to the url when user clicks on 'Read All Reviews" link on top right of the page after the stars.

**Review by davidltruong — APPROVED** [review]
Looks good

**Pull request merged**
