### PR TITLE
build star rating component

### PR DESCRIPTION
**Pull request by zxl3269117**

### CODE REVIEW

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
- Build the StarRating component to render rating view
- Put it in a new directory under `src/component/Sharables` so it can be used for any component needs to render rating
- Edited `calculateRating` in `clientHelper.js`. Still saved the quater rounding method commented out.
- Add CSS to render the UI properly.

**Review by mpmanzo — COMMENTED** [review]
@zxl3269117 
I like the simplicity of the ratings calculation, but I thinks slightly off. In order to round to the nearest 5% of total, I think it needs to be:

 let avgRating = (Math.round((total / count) / 5 * 100 / 5) * 5).toFixed(0);

Can you double check that before I approve? I'm fine getting rid of the other commented out code it replaces.

@mpmanzo

**Review by mpmanzo — APPROVED** [review]
Looks Good.

**Review by davidltruong — APPROVED** [review]
Looks good

**Pull request merged**
