### PR TITLE
Overview: CSS grid

### PR DESCRIPTION
**Pull request by zxl3269117**

### CODE REVIEW

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
Added a CSS grid to Overview component.

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
Updated className to be specific for Overview Component.

**Review by davidltruong — APPROVED** [review]
Looks good

**Review by mpmanzo — APPROVED** [review]

**Comment by mpmanzo** [comment]
Looks good.

**Pull request merged**
