### PR TITLE
set up test suite

### PR DESCRIPTION
**Pull request by zxl3269117**

### CODE REVIEW

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
Set up test suite. I did multiple changes:
1. installed `jest`, `babel-jest`, `jest-environment-jsdom`, and `@testing-library/react`
2. Update the test file name to "__tests__" and "overview.spec.js". Jest will recognize the test file names and run it when called `jest`.
3. Update the test script in package.json to `jest`.
4. Added an "index.js" file in "/client/src" to seperate out App. This change is for testing purpose. When App.jsx has ReactDOM, the test won't be able to run in a jsdom invironment.
5. Currently when running `npm test`, one test will fail from "relatedItemsSpec.js" due to no test is written in there.
6. Test I wrote are just testing if App and Overview components are rendering. Nothing else.

Happy to discuss if any of you want. It should be fine if we want to set up our own test in seperate file or all in one file.

**Review by davidltruong — CHANGES_REQUESTED** [review]
Since we are changing  index.js to be the entry point, webpack.config.js should also reflect that change. 

Everything else looks good. I will be adding my own render component test after this is merged

**Review by davidltruong — APPROVED** [review]
Looks good.

**Review by mpmanzo — APPROVED** [review]
Looks good. David, I'm not ready to add any tests. I'll follow your lead, but I think it will be cleaner to have all tests in one file. If you go that route, i'll delete the relatedItems file.

**Pull request merged**
