### PR TITLE
Overview: testing

### PR DESCRIPTION
**Pull request by zxl3269117**

### CODE REVIEW

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
- Add more tests to increase test coverage

**Review by mpmanzo — APPROVED** [review]
Looks good.

**Comment by zxl3269117** [comment]
@davidltruong @mpmanzo 
- Removed sampleData for initial rendering
- Folder name change from `/src/data` to `/src/mockFIles`. Update needed to all file refrencing `sampleData`
- Created a seperate file for mockServer under directory `/src/mockFiles/mockServer.js`. Included all GET request
- Commented out the `console.dir` for easier debugging during test writing
- Refactored test suite to render correct mockData.

**Review by mpmanzo — APPROVED** [review]
Looks fine.

**Review by davidltruong — APPROVED** [review]
Looks good to me

**Pull request merged**
